# Generated by Django 6.0.3 on 2026-03-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#007bff', max_length=20, verbose_name='颜色')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '客户标签',
                'verbose_name_plural': '客户标签',
                'db_table': 'customer_tags',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('customer_type', models.CharField(choices=[('dealer', '经销商'), ('terminal', '终端用户'), ('partner', '合作伙伴')], default='terminal', max_length=20, verbose_name='客户类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('blocked', '已封禁')], default='active', max_length=20, verbose_name='状态')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('equipment_count', models.IntegerField(default=0, verbose_name='设备数量')),
                ('tags', models.CharField(blank=True, help_text='多个标签用逗号分隔', max_length=500, verbose_name='标签')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50, verbose_name='服务类型')),
                ('description', models.TextField(verbose_name='服务描述')),
                ('service_date', models.DateTimeField(verbose_name='服务日期')),
                ('result', models.CharField(blank=True, max_length=100, verbose_name='服务结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_histories', to='customers.customer')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '服务历史',
                'verbose_name_plural': '服务历史',
                'db_table': 'service_histories',
                'ordering': ['-service_date'],
            },
        ),
    ]
