# Generated by Django 6.0.3 on 2026-03-07 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='equipment_count',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tags',
        ),
        migrations.AddField(
            model_name='customer',
            name='market_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_customers', to=settings.AUTH_USER_MODEL, verbose_name='市场经理'),
        ),
        migrations.AddField(
            model_name='customer',
            name='service_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviced_customers', to=settings.AUTH_USER_MODEL, verbose_name='服务经理'),
        ),
    ]
