# Generated by Django 6.0.3 on 2026-03-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='故障分类名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='故障代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faults.faultcategory')),
            ],
            options={
                'verbose_name': '故障分类',
                'verbose_name_plural': '故障分类',
                'db_table': 'fault_categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_no', models.CharField(max_length=50, unique=True, verbose_name='故障单号')),
                ('title', models.CharField(max_length=200, verbose_name='故障标题')),
                ('description', models.TextField(verbose_name='故障描述')),
                ('equipment_sn', models.CharField(blank=True, max_length=100, verbose_name='设备序列号')),
                ('equipment_name', models.CharField(blank=True, max_length=100, verbose_name='设备名称')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('source', models.CharField(choices=[('customer', '客户上报'), ('service', '客服上报'), ('field', '现场人员上报'), ('system', '系统自动')], default='customer', max_length=20, verbose_name='来源')),
                ('reporter_name', models.CharField(max_length=100, verbose_name='上报人')),
                ('reporter_phone', models.CharField(blank=True, max_length=20, verbose_name='上报人电话')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('assigned_time', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('resolve_time', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('solution', models.TextField(blank=True, verbose_name='解决方案')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_faults', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_faults', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fault_reports', to='customers.customer')),
                ('fault_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports', to='faults.faultcategory')),
            ],
            options={
                'verbose_name': '故障上报',
                'verbose_name_plural': '故障上报',
                'db_table': 'fault_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faults/images/', verbose_name='图片')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='faults.faultreport')),
            ],
            options={
                'verbose_name': '故障图片',
                'verbose_name_plural': '故障图片',
                'db_table': 'fault_images',
            },
        ),
        migrations.CreateModel(
            name='FaultComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='faults.faultreport')),
            ],
            options={
                'verbose_name': '故障备注',
                'verbose_name_plural': '故障备注',
                'db_table': 'fault_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='解决方案标题')),
                ('description', models.TextField(verbose_name='解决方案描述')),
                ('steps', models.TextField(blank=True, help_text='步骤用换行分隔', verbose_name='解决步骤')),
                ('applicable_models', models.CharField(blank=True, help_text='多个型号用逗号分隔', max_length=500, verbose_name='适用型号')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='成功率')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_solutions', to=settings.AUTH_USER_MODEL)),
                ('fault_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='faults.faultcategory')),
            ],
            options={
                'verbose_name': '解决方案',
                'verbose_name_plural': '解决方案',
                'db_table': 'solutions',
                'ordering': ['-use_count'],
            },
        ),
    ]
