# Generated by Django 6.0.3 on 2026-03-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='渠道名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='渠道代码')),
                ('carrier', models.CharField(max_length=100, verbose_name='承运商')),
                ('api_type', models.CharField(choices=[('kuaidi100', '快递100'), ('kuaidi', '快递鸟'), ('custom', '自定义')], default='kuaidi100', max_length=20, verbose_name='API类型')),
                ('api_config', models.JSONField(blank=True, default=dict, verbose_name='API配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '物流渠道',
                'verbose_name_plural': '物流渠道',
                'db_table': 'logistics_channels',
            },
        ),
        migrations.CreateModel(
            name='LogisticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, verbose_name='关联单号')),
                ('track_no', models.CharField(max_length=100, verbose_name='物流单号')),
                ('track_type', models.CharField(choices=[('inbound', '收件'), ('outbound', '发件')], max_length=20, verbose_name='物流类型')),
                ('sender_name', models.CharField(blank=True, max_length=100, verbose_name='发货人')),
                ('sender_phone', models.CharField(blank=True, max_length=20, verbose_name='发货人电话')),
                ('sender_address', models.CharField(blank=True, max_length=200, verbose_name='发货地址')),
                ('receiver_name', models.CharField(blank=True, max_length=100, verbose_name='收货人')),
                ('receiver_phone', models.CharField(blank=True, max_length=20, verbose_name='收货人电话')),
                ('receiver_address', models.CharField(blank=True, max_length=200, verbose_name='收货地址')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='物流状态')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='是否已签收')),
                ('current_location', models.CharField(blank=True, max_length=200, verbose_name='当前位置')),
                ('public_url', models.URLField(blank=True, verbose_name='公众查询链接')),
                ('url_expire_time', models.DateTimeField(blank=True, null=True, verbose_name='链接过期时间')),
                ('last_update_time', models.DateTimeField(blank=True, null=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='logistics.logisticschannel')),
            ],
            options={
                'verbose_name': '物流记录',
                'verbose_name_plural': '物流记录',
                'db_table': 'logistics_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_time', models.DateTimeField(verbose_name='轨迹时间')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('logistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='logistics.logisticsrecord')),
            ],
            options={
                'verbose_name': '物流轨迹',
                'verbose_name_plural': '物流轨迹',
                'db_table': 'logistics_traces',
                'ordering': ['trace_time'],
            },
        ),
    ]
