# Generated by Django 6.0.3 on 2026-03-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticsrecord',
            name='last_update_time',
        ),
        migrations.RemoveField(
            model_name='logisticsrecord',
            name='url_expire_time',
        ),
        migrations.AddField(
            model_name='logisticsrecord',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='开启后可通过链接分享物流信息', verbose_name='对外分享'),
        ),
    ]
