# Generated by Django 6.0.3 on 2026-03-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.productcategory')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品编码')),
                ('product_type', models.CharField(choices=[('part', '零配件'), ('semi', '半成品'), ('finished', '成品')], max_length=20, verbose_name='产品类型')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='规格型号')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本价')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='销售价')),
                ('min_stock', models.IntegerField(default=0, verbose_name='最小库存')),
                ('max_stock', models.IntegerField(default=0, verbose_name='最大库存')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='产品图片')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productcategory')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_no', models.CharField(max_length=50, unique=True, verbose_name='盘点单号')),
                ('warehouse', models.CharField(default='主仓库', max_length=100, verbose_name='仓库')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('checking', '盘点中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '库存盘点',
                'verbose_name_plural': '库存盘点',
                'db_table': 'stock_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCheckDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_quantity', models.IntegerField(verbose_name='账面数量')),
                ('actual_quantity', models.IntegerField(verbose_name='实际数量')),
                ('difference', models.IntegerField(verbose_name='差异数量')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('check_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.stockcheck')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': '盘点明细',
                'verbose_name_plural': '盘点明细',
                'db_table': 'stock_check_details',
            },
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('adjust', '调整'), ('check', '盘点')], max_length=20, verbose_name='记录类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('balance', models.IntegerField(verbose_name='库存余额')),
                ('related_order_no', models.CharField(blank=True, max_length=50, verbose_name='关联单号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_operations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.product')),
            ],
            options={
                'verbose_name': '库存记录',
                'verbose_name_plural': '库存记录',
                'db_table': 'stock_records',
                'ordering': ['-operate_time'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='仓库编码')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'warehouses',
            },
        ),
    ]
