# Generated by Django 6.0.3 on 2026-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_warehouse_to_stockrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='category',
            field=models.CharField(choices=[('heda', '禾大科技仓库'), ('dealer', '经销商仓库'), ('project', '项目仓库'), ('personal', '个人仓库'), ('regional', '区域仓库')], default='heda', max_length=20, verbose_name='仓库类别'),
        ),
    ]
