# Generated by Django 6.0.3 on 2026-03-07 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    """创建默认仓库类别并迁移现有数据"""
    WarehouseCategory = apps.get_model('inventory', 'WarehouseCategory')
    Warehouse = apps.get_model('inventory', 'Warehouse')

    # 创建默认类别
    default_categories = [
        {'name': '禾大科技仓库', 'code': 'heda', 'color': '#2563eb', 'icon': 'bi-building', 'sort_order': 0},
        {'name': '经销商仓库', 'code': 'dealer', 'color': '#0dcaf0', 'icon': 'bi-shop', 'sort_order': 1},
        {'name': '项目仓库', 'code': 'project', 'color': '#ffc107', 'icon': 'bi-briefcase', 'sort_order': 2},
        {'name': '个人仓库', 'code': 'personal', 'color': '#6c757d', 'icon': 'bi-person', 'sort_order': 3},
        {'name': '区域仓库', 'code': 'regional', 'color': '#20c997', 'icon': 'bi-globe', 'sort_order': 4},
    ]

    categories_map = {}
    for cat_data in default_categories:
        cat = WarehouseCategory.objects.create(**cat_data)
        categories_map[cat_data['code']] = cat

    # 更新现有仓库的类别关联（需要在新字段生效后执行）
    # 这里先返回映射，后续在迁移中处理


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_warehouse_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. 先创建WarehouseCategory表
        migrations.CreateModel(
            name='WarehouseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类别代码')),
                ('color', models.CharField(default='#6c757d', help_text='Bootstrap颜色类名或十六进制颜色值', max_length=20, verbose_name='颜色标识')),
                ('icon', models.CharField(default='bi-building', help_text='Bootstrap Icons图标类名', max_length=50, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '仓库类别',
                'verbose_name_plural': '仓库类别',
                'db_table': 'warehouse_categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        # 2. 添加临时字段存储旧的category值
        migrations.AddField(
            model_name='warehouse',
            name='category_old',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        # 3. 复制旧值到临时字段
        migrations.RunSQL(
            "UPDATE warehouses SET category_old = category",
            "UPDATE warehouses SET category = category_old"
        ),
        # 4. 创建默认类别
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
        # 5. 删除旧的category字段
        migrations.RemoveField(
            model_name='warehouse',
            name='category',
        ),
        # 6. 添加新的category字段（外键）
        migrations.AddField(
            model_name='warehouse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='inventory.warehousecategory', verbose_name='仓库类别'),
        ),
        # 7. 根据旧值更新新的外键关联
        migrations.RunSQL(
            """
            UPDATE warehouses SET category_id = (
                SELECT id FROM warehouse_categories WHERE code = warehouses.category_old
            )
            """,
            "UPDATE warehouses SET category_old = (SELECT code FROM warehouse_categories WHERE id = warehouses.category_id)"
        ),
        # 8. 删除临时字段
        migrations.RemoveField(
            model_name='warehouse',
            name='category_old',
        ),
        # 9. 创建InventoryTabConfig表
        migrations.CreateModel(
            name='InventoryTabConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_key', models.CharField(choices=[('overview', '库存概览'), ('inbound', '入库'), ('outbound', '出库'), ('check', '盘点'), ('report', '库存报表'), ('warehouse', '仓库管理')], max_length=20, verbose_name='Tab标识')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_tab_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '库存Tab配置',
                'verbose_name_plural': '库存Tab配置',
                'db_table': 'inventory_tab_configs',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('user', 'tab_key')},
            },
        ),
    ]
