# Generated by Django 6.0.3 on 2026-03-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('part', '配件价格'), ('labor', '工时费'), ('travel', '交通费')], max_length=20, verbose_name='配置类型')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=50, verbose_name='编码')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '价格配置',
                'verbose_name_plural': '价格配置',
                'db_table': 'price_configs',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(max_length=50, unique=True, verbose_name='报价单号')),
                ('repair_order_no', models.CharField(blank=True, max_length=50, verbose_name='返修单号')),
                ('customer_name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('customer_contact', models.CharField(blank=True, max_length=100, verbose_name='客户联系人')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='客户电话')),
                ('parts_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='配件费用')),
                ('labor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工时费用')),
                ('travel_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='交通费用')),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他费用')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='合计金额')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已审批'), ('rejected', '已拒绝'), ('confirmed', '已确认'), ('expired', '已过期')], default='draft', max_length=20, verbose_name='状态')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approve_remark', models.TextField(blank=True, verbose_name='审批意见')),
                ('confirmed_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quote_quotes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '报价单',
                'verbose_name_plural': '报价单',
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('part', '配件'), ('labor', '工时'), ('travel', '交通'), ('other', '其他')], max_length=20, verbose_name='类型')),
                ('item_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='规格')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'verbose_name': '报价明细',
                'verbose_name_plural': '报价明细',
                'db_table': 'quote_items',
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('content', models.JSONField(default=dict, verbose_name='模板内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quote_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '报价模板',
                'verbose_name_plural': '报价模板',
                'db_table': 'quote_templates',
            },
        ),
    ]
