# Generated by Django 6.0.3 on 2026-03-09 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_warehouse_category_model'),
        ('quotes', '0002_remove_quote_repair_order_no_quote_repair_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='approve_remark',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='approve_time',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='confirmed_time',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='customer_contact',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='other_amount',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='repair_order',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='travel_amount',
        ),
        migrations.AddField(
            model_name='priceconfig',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_configs', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='报价名称'),
        ),
        migrations.AddField(
            model_name='quote',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='生效日期'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='priceconfig',
            name='config_type',
            field=models.CharField(choices=[('part', '成品配件'), ('labor', '工时费')], max_length=20, verbose_name='配置类型'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '生效中'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='item_type',
            field=models.CharField(choices=[('part', '成品配件'), ('labor', '工时')], max_length=20, verbose_name='类型'),
        ),
    ]
