# Generated by Django 6.0.3 on 2026-03-09 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_quote_approve_remark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceconfig',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_configs', to='quotes.priceconfig'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='quotes.quoteitem'),
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='系列名称')),
                ('description', models.TextField(blank=True, verbose_name='系列描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '产品系列',
                'verbose_name_plural': '产品系列',
                'db_table': 'product_series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='产品名称')),
                ('repair_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='维修价格')),
                ('labor_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='维修工时费')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('status', models.CharField(choices=[('active', '上架'), ('inactive', '下架')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quote_products', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_products', to='quotes.productseries')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'quote_products',
                'ordering': ['-created_at'],
            },
        ),
    ]
