# Generated by Django 6.0.3 on 2026-03-09 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='手机名称')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='手机型号')),
                ('user', models.CharField(blank=True, max_length=50, verbose_name='使用者')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='手机号码')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_phones', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '手机管理',
                'verbose_name_plural': '手机管理',
                'db_table': 'sms_phones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='手机号码')),
                ('content', models.TextField(verbose_name='短信内容')),
                ('received_date', models.DateField(verbose_name='接收日期')),
                ('received_time', models.TimeField(verbose_name='接收时间')),
                ('sender', models.CharField(blank=True, max_length=50, verbose_name='发送方')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_records', to='sms.phone', verbose_name='关联手机')),
            ],
            options={
                'verbose_name': '短信记录',
                'verbose_name_plural': '短信记录',
                'db_table': 'sms_records',
                'ordering': ['-received_date', '-received_time'],
            },
        ),
    ]
