# Generated by Django 6.0.3 on 2026-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, verbose_name='配置名称')),
                ('db_type', models.CharField(choices=[('sqlite', 'SQLite'), ('mysql', 'MySQL')], default='sqlite', max_length=20, verbose_name='数据库类型')),
                ('mysql_host', models.CharField(blank=True, default='localhost', max_length=100, verbose_name='MySQL主机')),
                ('mysql_port', models.IntegerField(default=3306, verbose_name='MySQL端口')),
                ('mysql_user', models.CharField(blank=True, max_length=50, verbose_name='MySQL用户名')),
                ('mysql_password', models.CharField(blank=True, max_length=100, verbose_name='MySQL密码')),
                ('mysql_database', models.CharField(blank=True, max_length=50, verbose_name='MySQL数据库名')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据库配置',
                'verbose_name_plural': '数据库配置',
                'db_table': 'system_database_config',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('is_public', models.BooleanField(default=False, help_text='前端是否可读', verbose_name='公开配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_config',
            },
        ),
    ]
