# Generated by Django 6.0.3 on 2026-03-09 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='姓名')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('manager', '经理'), ('staff', '员工'), ('viewer', '访客')], default='staff', max_length=20, verbose_name='角色')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='部门')),
                ('page_permissions', models.JSONField(blank=True, default=list, help_text='用户可访问的页面列表', verbose_name='页面权限')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户权限',
                'verbose_name_plural': '用户权限',
                'db_table': 'user_page_permissions',
            },
        ),
    ]
