# Generated by Django 6.0.3 on 2026-03-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='full_name',
        ),
    ]
