# Generated by Django 6.0.3 on 2026-03-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_userpermissions_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='姓名'),
        ),
    ]
