# Generated by Django 6.0.3 on 2026-03-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='权限')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('start', '开始'), ('approval', '审批'), ('task', '任务'), ('condition', '条件'), ('end', '结束')], max_length=20, verbose_name='节点类型')),
                ('assignee_type', models.CharField(choices=[('user', '指定用户'), ('role', '角色'), ('dept', '部门'), ('initiator', '申请人')], default='role', max_length=20, verbose_name='处理人类型')),
                ('assignee_value', models.CharField(blank=True, max_length=100, verbose_name='处理人值')),
                ('form_config', models.JSONField(blank=True, default=dict, verbose_name='节点表单配置')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
                ('timeout_hours', models.IntegerField(default=0, verbose_name='超时小时数')),
            ],
            options={
                'verbose_name': '流程节点',
                'verbose_name_plural': '流程节点',
                'db_table': 'workflow_nodes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='流程代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('form_config', models.JSONField(blank=True, default=dict, verbose_name='表单配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '流程类型',
                'verbose_name_plural': '流程类型',
                'db_table': 'workflow_types',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='组织名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='组织代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_depts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workflows.organization')),
            ],
            options={
                'verbose_name': '组织单元',
                'verbose_name_plural': '组织单元',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(blank=True, max_length=50, verbose_name='员工工号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.organization')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='workflows.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='流程标题')),
                ('business_type', models.CharField(blank=True, max_length=50, verbose_name='业务类型')),
                ('business_id', models.CharField(blank=True, max_length=50, verbose_name='业务ID')),
                ('status', models.CharField(choices=[('running', '进行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('rejected', '已拒绝')], default='running', max_length=20, verbose_name='状态')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='表单数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL)),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflownode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflows.workflowtype')),
            ],
            options={
                'verbose_name': '流程实例',
                'verbose_name_plural': '流程实例',
                'db_table': 'workflow_instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('rejected', '已拒绝'), ('transferred', '已转交')], default='pending', max_length=20, verbose_name='状态')),
                ('comment', models.TextField(blank=True, verbose_name='处理意见')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflows.workflowinstance')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflownode')),
            ],
            options={
                'verbose_name': '流程任务',
                'verbose_name_plural': '流程任务',
                'db_table': 'workflow_tasks',
            },
        ),
        migrations.AddField(
            model_name='workflownode',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflowtype'),
        ),
    ]
