# Generated by Django 6.0.3 on 2026-03-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('inventory', '库存预警'), ('repair', '维修周期预警'), ('fault', '故障预警'), ('quote', '报价预警')], max_length=20, verbose_name='规则类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('condition_config', models.JSONField(default=dict, verbose_name='条件配置')),
                ('notify_config', models.JSONField(default=dict, verbose_name='通知配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '预警规则',
                'verbose_name_plural': '预警规则',
                'db_table': 'alert_rules',
            },
        ),
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='预警标题')),
                ('content', models.TextField(verbose_name='预警内容')),
                ('trigger_data', models.JSONField(default=dict, verbose_name='触发数据')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('handled', '已处理'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='状态')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handle_remark', models.TextField(blank=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_alerts', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='analytics.alertrule')),
            ],
            options={
                'verbose_name': '预警记录',
                'verbose_name_plural': '预警记录',
                'db_table': 'alert_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仪表盘名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='仪表盘代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('layout_config', models.JSONField(default=dict, verbose_name='布局配置')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, related_name='dashboards', to='workflows.role')),
            ],
            options={
                'verbose_name': '仪表盘',
                'verbose_name_plural': '仪表盘',
                'db_table': 'dashboards',
            },
        ),
        migrations.CreateModel(
            name='ChartConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='图表名称')),
                ('chart_type', models.CharField(choices=[('line', '折线图'), ('bar', '柱状图'), ('pie', '饼图'), ('table', '表格'), ('gauge', '仪表盘'), ('scatter', '散点图')], max_length=20, verbose_name='图表类型')),
                ('data_source', models.CharField(choices=[('fault', '故障数据'), ('repair', '维修数据'), ('inventory', '库存数据'), ('customer', '客户数据'), ('quote', '报价数据')], max_length=100, verbose_name='数据源')),
                ('query_config', models.JSONField(default=dict, verbose_name='查询配置')),
                ('display_config', models.JSONField(default=dict, verbose_name='展示配置')),
                ('x', models.IntegerField(default=0, verbose_name='X坐标')),
                ('y', models.IntegerField(default=0, verbose_name='Y坐标')),
                ('width', models.IntegerField(default=4, verbose_name='宽度')),
                ('height', models.IntegerField(default=3, verbose_name='高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charts', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='analytics.dashboard')),
            ],
            options={
                'verbose_name': '图表配置',
                'verbose_name_plural': '图表配置',
                'db_table': 'chart_configs',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('data_source', models.CharField(max_length=100, verbose_name='数据源')),
                ('query_config', models.JSONField(default=dict, verbose_name='查询配置')),
                ('field_mapping', models.JSONField(default=dict, verbose_name='字段映射')),
                ('export_config', models.JSONField(default=dict, verbose_name='导出配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '报表模板',
                'verbose_name_plural': '报表模板',
                'db_table': 'report_templates',
            },
        ),
    ]
