# Generated by Django 6.0.3 on 2026-03-06 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('local', '本地模型'), ('custom', '自定义')], default='openai', max_length=20, verbose_name='AI提供商')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API Key')),
                ('api_base', models.CharField(blank=True, max_length=200, verbose_name='API Base URL')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='模型名称')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('max_tokens', models.IntegerField(default=2000, verbose_name='Max Tokens')),
                ('embedding_provider', models.CharField(blank=True, max_length=50, verbose_name='Embedding提供商')),
                ('embedding_model', models.CharField(blank=True, max_length=50, verbose_name='Embedding模型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='设为默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI配置',
                'verbose_name_plural': 'AI配置',
                'db_table': 'ai_configs',
            },
        ),
        migrations.CreateModel(
            name='IntentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='意图名称')),
                ('intent', models.CharField(max_length=50, verbose_name='意图标识')),
                ('patterns', models.JSONField(default=list, verbose_name='匹配模式')),
                ('response_template', models.TextField(blank=True, verbose_name='响应模板')),
                ('action_type', models.CharField(blank=True, max_length=50, verbose_name='动作类型')),
                ('action_config', models.JSONField(blank=True, default=dict, verbose_name='动作配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '意图模式',
                'verbose_name_plural': '意图模式',
                'db_table': 'intent_patterns',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='对话标题')),
                ('conversation_type', models.CharField(choices=[('chat', '智能问答'), ('fault_predict', '故障预判'), ('data_query', '数据查询'), ('work_order', '工单创建')], default='chat', max_length=20, verbose_name='对话类型')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='上下文数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI对话',
                'verbose_name_plural': 'AI对话',
                'db_table': 'ai_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='知识库名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('kb_type', models.CharField(choices=[('document', '文档'), ('faq', 'FAQ'), ('case', '维修案例'), ('manual', '手册')], default='document', max_length=20, verbose_name='知识库类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_bases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'knowledge_bases',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('content', models.TextField(verbose_name='文档内容')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('related_equipment_models', models.CharField(blank=True, max_length=500, verbose_name='关联设备型号')),
                ('related_fault_codes', models.CharField(blank=True, max_length=200, verbose_name='关联故障代码')),
                ('embedding_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='向量化状态')),
                ('embedding_error', models.TextField(blank=True, verbose_name='向量化错误信息')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('useful_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_docs', to=settings.AUTH_USER_MODEL)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ai_assistant.knowledgebase')),
            ],
            options={
                'verbose_name': '知识文档',
                'verbose_name_plural': '知识文档',
                'db_table': 'knowledge_documents',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('intent', models.CharField(blank=True, max_length=50, verbose_name='意图')),
                ('entities', models.JSONField(blank=True, default=dict, verbose_name='实体')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation')),
            ],
            options={
                'verbose_name': '对话消息',
                'verbose_name_plural': '对话消息',
                'db_table': 'ai_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
